import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ReactQueryProvider from "@/components/providers/query-client-provider";
import AuthProvider from "@/components/providers/auth-provider";

import localFont from "next/font/local"

const inter = Inter({ 
	subsets: ["latin"],
	variable: "--font-sans",
});

const fontHeading = localFont({
  src: "../../public/fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading",
})

export const metadata: Metadata = {
  title: "Recipy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
		<body
			className={cn(
				"min-h-screen bg-background font-sans antialiased",
				inter.variable,
				fontHeading.variable,
			)}
		>
			<ReactQueryProvider>
				<AuthProvider>
					{children}
				</AuthProvider>
			</ReactQueryProvider>
      	</body>
    </html>
  );
}
