# Generated by Django 5.0.6 on 2024-07-01 10:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('cheap', models.BooleanField(default=False)),
                ('healthScore', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('readyInMinutes', models.IntegerField(blank=True, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('cuisines', wagtail.fields.StreamField([('cuisine', wagtail.blocks.CharBlock(required=True))], blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('analyzedInstructions', wagtail.fields.StreamField([('instruction', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=True)), ('steps', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.IntegerBlock(required=True)), ('step', wagtail.blocks.TextBlock(required=True))])))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.IntegerField()),
                ('aisle', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('nameClean', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('recipe', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipepage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
