# Generated by Django 5.0.6 on 2024-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipepage',
            name='ingredients',
            field=models.ManyToManyField(to='recipe.ingredient'),
        ),
    ]
