<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-01 13:53
=======
# Generated by Django 5.0.6 on 2024-07-02 07:44
>>>>>>> main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_ingredient_recipe_recipepage_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipePage',
            new_name='Recipe',
        ),
    ]
