# Generated by Django 5.0.6 on 2024-07-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_recipepage_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='analyzedInstructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cuisines',
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('step', models.TextField()),
                ('length_number', models.IntegerField(blank=True, null=True)),
                ('length_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment', models.ManyToManyField(blank=True, to='recipe.equipment')),
                ('ingredients', models.ManyToManyField(blank=True, to='recipe.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzedInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('steps', models.ManyToManyField(blank=True, to='recipe.step')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='analyzedInstructions',
            field=models.ManyToManyField(blank=True, to='recipe.analyzedinstruction'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisines',
            field=models.ManyToManyField(blank=True, to='recipe.cuisine'),
        ),
    ]
