# Generated by Django 5.0.6 on 2024-07-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_cuisine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='image',
        ),
    ]
