# Generated by Django 5.0.6 on 2024-07-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='users',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='analyzedInstructions',
            field=models.ManyToManyField(blank=True, to='recipe.analyzedinstruction', verbose_name='Analyzed Instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cheap',
            field=models.BooleanField(default=False, verbose_name='Cheap?'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisines',
            field=models.ManyToManyField(blank=True, to='recipe.cuisine', verbose_name='Cuisines'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='healthScore',
            field=models.IntegerField(default=0, verbose_name='Health Score'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipe.ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='readyInMinutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time to prepare (in minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name of the recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=False, verbose_name='Vegan?'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='Vegetarian?'),
        ),
    ]
