# Generated by Django 5.0.6 on 2024-07-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_remove_recipe_users_and_more'),
        ('user', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(to='recipe.recipe'),
        ),
    ]
